version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: fullstack-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fullstack-app-api
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
